{% set name = "ooipy" %}
{% set version = "1.1.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 208337fcc1b1217a394f7ea4fc3030bf72ffdbe961f776a1f53864a3fcef7874

build:
  number: 0
  noarch: python
  script:
    - export SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}    # [unix]
    - set SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}    # [win]
    - {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools >=45
    - setuptools_scm >=3.4
    - toml
  run:
    - aiohttp
    - fsspec
    - obspy
    - python >=3.6
    - pandas

test:
  imports:
    - ooipy
    - ooipy.hydrophone
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ooipy/ooipy
  summary: A python toolbox for acquiring and analyzing Ocean Obvservatories Initiative (OOI) Data
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lsetiawan
    - John-Ragland
    - FelixSchwock
